[package]
name = "graph"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
async-graphql = "7.0.14"
async-graphql-actix-web = "7.0.14"
tokio = { version = "1.39.3", features = ["full"] } # For async runtime

